media: public/assets/images


content:
  - name: references
    label: "Exhibits"
    type: collection
    path: "src/content/docs"
    icon: "book"
    filename: "{fields.slug}.md"
    format: "yaml-frontmatter"
    exclude: [README.md]
    fields:
      - name: "title"
        label: "Exhibit Title"
        type: "string"
        required: true
      - name: "description"
        label: "Description"
        type: "text"
        description: "A short summary of the exhibit for SEO and previews."
      - name: "date"
        label: "Publication Date"
        type: "string"
      - name: "hero"
        label: "Hero Section"
        type: "object"
        fields:
          - name: "title"
            label: "Hero Title"
            type: "string"
          - name: "tagline"
            label: "Tagline"
            type: "string"
          - name: "image"
            label: "Hero Image"
            type: "object"
            fields:
              - name: "file"
                label: "Image Source"
                type: "image"
                list: true
                options:
                  upload_dir: "src/assets"  # Your image directory
                  extensions: [jpg, jpeg, png, svg]
              - name: "alt"
                label: "Alternative Text"
                type: "string"
      - name: "slug"
        label: "Slug"
        type: "string"
        required: true
        description: "The URL path for this exhibit page."
      - name: "tableOfContents"
        label: "Table of Contents"
        type: "object"
        fields:
          - name: "minHeadingLevel"
            label: "Minimum Heading Level"
            type: "number"
            default: 2
          - name: "maxHeadingLevel"
            label: "Maximum Heading Level"
            type: "number"
            default: 3
      - name: "template"
        label: "Template"
        type: "string"
        default: "doc"
        description: "Defines the template type for rendering this page."
      - name: "body"
        label: "Page Body"
        type: "rich-text"  # or use "rich-text" for WYSIWYG editor
        options: 
          format: markdown
 
        