# CMS Configuration for Starlight Astro Exhibits
collections:
  # Collection for exhibits under references
  references:
    label: "Exhibits"
    path: "src/content/reference/{slug}.md"
    fields:
      - name: "title"
        label: "Exhibit Title"
        type: "string"
        required: true
      - name: "description"
        label: "Description"
        type: "text"
        description: "A short summary of the exhibit for SEO and previews."
      - name: "date"
        label: "Publication Date"
        type: "date"
        required: false
      - name: "slug"
        label: "Slug"
        type: "string"
        required: true
        description: "The URL path for this exhibit page."
      - name: "hero"
        label: "Hero Section"
        type: "group"
        fields:
          - name: "title"
            label: "Hero Title"
            type: "string"
          - name: "tagline"
            label: "Tagline"
            type: "string"
            required: false
      - name: "tableOfContents"
        label: "Table of Contents"
        type: "group"
        description: "Configure TOC heading levels."
        fields:
          - name: "minHeadingLevel"
            label: "Minimum Heading Level"
            type: "number"
            default: 2
          - name: "maxHeadingLevel"
            label: "Maximum Heading Level"
            type: "number"
            default: 5
      - name: "template"
        label: "Template"
        type: "string"
        default: "doc"
        description: "Defines the template type for rendering this page."
      - name: "content"
        label: "Page Content"
        type: "markdown"
        description: "The main content of the exhibit page, written in markdown."