# CMS Configuration for Starlight Astro
collections:
  # References collection for exhibits
  references:
    label: "Exhibits"
    path: "src/content/reference/{slug}.md"
    fields:
      - name: "title"
        label: "Exhibit Title"
        type: "string"
        required: true
      - name: "description"
        label: "Description"
        type: "text"
        description: "A short summary of the exhibit for SEO and previews."
      - name: "slug"
        label: "Slug"
        type: "string"
        description: "The URL path for this exhibit page."
        required: true
      - name: "draft"
        label: "Draft"
        type: "boolean"
        default: false
        description: "Mark as draft to hide in production."
      - name: "order"
        label: "Order"
        type: "number"
        description: "The order in the sidebar (optional)."
      - name: "content"
        label: "Page Content"
        type: "markdown"
        description: "The main content of the exhibit."